run:
  timeout: 5m
  tests: true

issues:
  exclude-dirs:
    - vendor
    - migrations
  exclude-files:
    - ".*\\.pb\\.go"
    - ".*\\.gen\\.go"
    - ".*\\.mock\\.go"

linters-settings:
  goconst:
    min-len: 3
    min-occurrences: 3

  gocyclo:
    min-complexity: 15

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - unused
    - goconst
    - gofmt
    - misspell
  disable:
    - dupl
    - lll
