// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/juzu400/avito-internship/internal/domain"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(ctx context.Context, id domain.UserID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), ctx, id)
}

// SetIsActive mocks base method.
func (m *MockUserRepository) SetIsActive(ctx context.Context, id domain.UserID, active bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetIsActive", ctx, id, active)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetIsActive indicates an expected call of SetIsActive.
func (mr *MockUserRepositoryMockRecorder) SetIsActive(ctx, id, active interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIsActive", reflect.TypeOf((*MockUserRepository)(nil).SetIsActive), ctx, id, active)
}

// MockTeamRepository is a mock of TeamRepository interface.
type MockTeamRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTeamRepositoryMockRecorder
}

// MockTeamRepositoryMockRecorder is the mock recorder for MockTeamRepository.
type MockTeamRepositoryMockRecorder struct {
	mock *MockTeamRepository
}

// NewMockTeamRepository creates a new mock instance.
func NewMockTeamRepository(ctrl *gomock.Controller) *MockTeamRepository {
	mock := &MockTeamRepository{ctrl: ctrl}
	mock.recorder = &MockTeamRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamRepository) EXPECT() *MockTeamRepositoryMockRecorder {
	return m.recorder
}

// GetByMemberID mocks base method.
func (m *MockTeamRepository) GetByMemberID(ctx context.Context, userID domain.UserID) (*domain.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByMemberID", ctx, userID)
	ret0, _ := ret[0].(*domain.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByMemberID indicates an expected call of GetByMemberID.
func (mr *MockTeamRepositoryMockRecorder) GetByMemberID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByMemberID", reflect.TypeOf((*MockTeamRepository)(nil).GetByMemberID), ctx, userID)
}

// GetByName mocks base method.
func (m *MockTeamRepository) GetByName(ctx context.Context, name string) (*domain.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*domain.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockTeamRepositoryMockRecorder) GetByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockTeamRepository)(nil).GetByName), ctx, name)
}

// GetTeamsByMemberIDs mocks base method.
func (m *MockTeamRepository) GetTeamsByMemberIDs(ctx context.Context, userIDs []domain.UserID) (map[domain.UserID]*domain.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamsByMemberIDs", ctx, userIDs)
	ret0, _ := ret[0].(map[domain.UserID]*domain.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamsByMemberIDs indicates an expected call of GetTeamsByMemberIDs.
func (mr *MockTeamRepositoryMockRecorder) GetTeamsByMemberIDs(ctx, userIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamsByMemberIDs", reflect.TypeOf((*MockTeamRepository)(nil).GetTeamsByMemberIDs), ctx, userIDs)
}

// UpsertTeam mocks base method.
func (m *MockTeamRepository) UpsertTeam(ctx context.Context, team *domain.Team) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTeam", ctx, team)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertTeam indicates an expected call of UpsertTeam.
func (mr *MockTeamRepositoryMockRecorder) UpsertTeam(ctx, team interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTeam", reflect.TypeOf((*MockTeamRepository)(nil).UpsertTeam), ctx, team)
}

// MockPullRequestRepository is a mock of PullRequestRepository interface.
type MockPullRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPullRequestRepositoryMockRecorder
}

// MockPullRequestRepositoryMockRecorder is the mock recorder for MockPullRequestRepository.
type MockPullRequestRepositoryMockRecorder struct {
	mock *MockPullRequestRepository
}

// NewMockPullRequestRepository creates a new mock instance.
func NewMockPullRequestRepository(ctrl *gomock.Controller) *MockPullRequestRepository {
	mock := &MockPullRequestRepository{ctrl: ctrl}
	mock.recorder = &MockPullRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPullRequestRepository) EXPECT() *MockPullRequestRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPullRequestRepository) Create(ctx context.Context, pr *domain.PullRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, pr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPullRequestRepositoryMockRecorder) Create(ctx, pr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPullRequestRepository)(nil).Create), ctx, pr)
}

// GetByID mocks base method.
func (m *MockPullRequestRepository) GetByID(ctx context.Context, id domain.PullRequestID) (*domain.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPullRequestRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPullRequestRepository)(nil).GetByID), ctx, id)
}

// GetPullRequestReviewerStats mocks base method.
func (m *MockPullRequestRepository) GetPullRequestReviewerStats(ctx context.Context) ([]domain.PullRequestReviewersStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPullRequestReviewerStats", ctx)
	ret0, _ := ret[0].([]domain.PullRequestReviewersStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPullRequestReviewerStats indicates an expected call of GetPullRequestReviewerStats.
func (mr *MockPullRequestRepositoryMockRecorder) GetPullRequestReviewerStats(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPullRequestReviewerStats", reflect.TypeOf((*MockPullRequestRepository)(nil).GetPullRequestReviewerStats), ctx)
}

// GetReviewerAssignmentStats mocks base method.
func (m *MockPullRequestRepository) GetReviewerAssignmentStats(ctx context.Context) ([]domain.ReviewerAssignmentStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReviewerAssignmentStats", ctx)
	ret0, _ := ret[0].([]domain.ReviewerAssignmentStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReviewerAssignmentStats indicates an expected call of GetReviewerAssignmentStats.
func (mr *MockPullRequestRepositoryMockRecorder) GetReviewerAssignmentStats(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReviewerAssignmentStats", reflect.TypeOf((*MockPullRequestRepository)(nil).GetReviewerAssignmentStats), ctx)
}

// ListByReviewer mocks base method.
func (m *MockPullRequestRepository) ListByReviewer(ctx context.Context, reviewerID domain.UserID) ([]*domain.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByReviewer", ctx, reviewerID)
	ret0, _ := ret[0].([]*domain.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByReviewer indicates an expected call of ListByReviewer.
func (mr *MockPullRequestRepositoryMockRecorder) ListByReviewer(ctx, reviewerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByReviewer", reflect.TypeOf((*MockPullRequestRepository)(nil).ListByReviewer), ctx, reviewerID)
}

// Merge mocks base method.
func (m *MockPullRequestRepository) Merge(ctx context.Context, id domain.PullRequestID, mergedAt time.Time) (*domain.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Merge", ctx, id, mergedAt)
	ret0, _ := ret[0].(*domain.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Merge indicates an expected call of Merge.
func (mr *MockPullRequestRepositoryMockRecorder) Merge(ctx, id, mergedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Merge", reflect.TypeOf((*MockPullRequestRepository)(nil).Merge), ctx, id, mergedAt)
}

// Update mocks base method.
func (m *MockPullRequestRepository) Update(ctx context.Context, pr *domain.PullRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, pr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPullRequestRepositoryMockRecorder) Update(ctx, pr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPullRequestRepository)(nil).Update), ctx, pr)
}
